I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 306, in script
    
  File "game/script.rpy", line 306, in <module>
    
NameError: name 'stand' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 306, in script
    
  File "C:\Users\Benjamin Shu\Documents\renpy-6.99.14.1-sdk\renpy\ast.py", line 1151, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "C:\Users\Benjamin Shu\Documents\renpy-6.99.14.1-sdk\renpy\ast.py", line 1110, in show_imspec
    at_list = [ renpy.python.py_eval(i) for i in at_list ]
  File "C:\Users\Benjamin Shu\Documents\renpy-6.99.14.1-sdk\renpy\python.py", line 1944, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\Benjamin Shu\Documents\renpy-6.99.14.1-sdk\renpy\python.py", line 1937, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 306, in <module>
    
NameError: name 'stand' is not defined

Windows-8-6.2.9200
Ren'Py 7.1.1.929
Finals Week 1.0
Wed Dec 12 03:39:27 2018
